server:
  port: 8301
spring:
  application:
    name: service-vod
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_vod?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: @pom.nacos.dev.namespace@

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/h2s/ggkt/service_vod/mapper/xml/*.xml

tencent:
  cos:
    file:
      secretKey: sdPE1gAPQceXQJ60iGbv76zmOp57uVt5
      secretId: AKIDW4QcovvtohUCmEUVJ8FMTZnwufEcqxrk
      region: ap-chongqing
      bucketName: ggkt-file-by-h2s-1310090924