server:
  port: 8333

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: @pom.nacos.dev.namespace@
    gateway:
      routes:
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/*/vod/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
        - id: service-activity
          uri: lb://service-activity
          predicates:
            - Path=/*/activity/**

